version: "3.9"

services:
  autocomplete-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
  autocomplete-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
