FROM node:12-buster-slim as base

WORKDIR /app

COPY ./frontend /app/
COPY /common/ ../common

RUN npm install
RUN CI=true npm test
RUN npm run build

FROM nginx:1.19.3-alpine

ENV NGINX_PORT 3000
COPY --from=base /app/build /usr/share/nginx/html
COPY ./frontend/default.conf /etc/nginx/conf.d/

EXPOSE 3000